version: '3.7'
services:
  express:
    build:
      dockerfile: ./Dockerfile
      context: .
    restart: always
    container_name: express
    volumes:
    - ./.env:/app/.env
    ports:
      - "3000:3000"
